# 端口
server:
  port: 8093

## mysql的配置, 使用druid数据库连接池, mysql+druid配置放在了一起
#spring:
#  datasource:
#    druid:
#      username: root
#      password: 123456
#      url: jdbc:mysql://localhost:3306/myschool?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      # 初始化大小
#      initialSize: 3
#      # 最小
#      minIdle: 5
#      # 最大
#      maxActive: 20
#      # 最长等待时间
#      maxWait: 30000
#      # 配置间隔多久才进行一次检测, 检测需要关闭的空闲连接, 单位是毫秒，
#      timeBetweenEvictionRunsMillis:
#      # 配置一个连接在池中最小生存的时间，单位是毫秒
#      minEvictableIdleTimeMillis: 300000
#      maxEvictableIdleTimeMillis: 900000
#      validationQuery: SELECT 1 FROM DUAL
#      testWhileIdle: true
#      testOnBorrow: false
#      testOnReturn: false
#      # 打开PSCache，并且指定每个连接上PSCache的大小
#      poolPreparedStatements: true
#      maxPoolPreparedStatementPerConnectionSize: 20
##      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
##      filters: stat,wall,log4j
##      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录, 合并多个DruidDataSource的监控数据
##      useGlobalDataSourceStat: true
##      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
##      connectionProperties: druid.stat.mergeSql=true
##      druid.stat.slowSqlMillis: 10000
#      web-stat-filter:
#        enabled: true
#        url-pattern: "/*"
#        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
#        session-stat-max-count: 1000
#        session-stat-enable: true
#        profile-enable: true
#      stat-view-servlet:
#        enabled: true
#        url-pattern: "/druid/*"
#        login-username: root
#        login-password: root
#        allow: 127.0.0.1
#        reset-enable: true
#    type: com.alibaba.druid.pool.DruidDataSource
#    url:
#    username: admin
#    password: 123456
#    driver-class-name:
#    filters: stat,wall,slf4j
#    maxActive: 20

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myschool?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    password: 123456
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
    # 下面为连接池的补充设置，应用到上面所有数据源中
    type: com.alibaba.druid.pool.DruidDataSource

    # 初始化大小，最小，最大
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true