spring:
  datasource:
    username: root
    password: renjiaxin
#    需要加上时区，这点得注意
    url: jdbc:mysql://localhost:3306/jdbc?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
#    schema:
#      - classpath:department.sql
#    initialization-mode: ALWAYS
#    一定要注意classpath:后面没有空格
#    schema-username: root
#    schema-password: renjiaxin
#    下面的废弃了
#    driver-class-name: com.mysql.jdbc.Driver